spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
  liquibase:
    enabled: false
shop:
  url: localhost:8081
metric:
  url: localhost:8081
application:
  security:
    secret-key: SECRET_KEY
    expired-at-in-minutes: 3600000
    allowed-endpoints: [ '/', 'login', '/css/**', '/js/**', '/api/oauth/**',
                         '/swagger-ui.html', '/swagger-ui.css', '/swagger-ui/**', '/swagger-resources',
                         '/swagger-resources/**', '/configuration/ui', '/configuration/security', '/webjars/**',
                         '/v2/api-docs/**' ]
    login-endpoint: '/api/login'